# Default values for gotify.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gotify/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: Prefix
  ingressClassName: ""
  tls:
    enabled: false
    secrets:
    - secretName: chart-example-tls
      hosts:
        - chart-example.local

config:
  enabled: true              # Enable ConfigMap creation
  data:
    APP_ENV: "production"    # Key and value for data ConfigMap

secret:
  enabled: true              # Enable Secret creation
  data:
    DB_PASSWORD: "my-password"  # Key and value (secret) in base64 will be automatically encoded
    API_KEY: "topsecret"
  # If you need unencoded values, use stringData (Kubernetes will encode it itself):
#  stringData: {}

# List of environment variables to be passed to the container
env:
  enabled: false         # Enable or disable adding env variables
  values:
  - name: ENV_VAR_NAME
    value: "value"
  - name: ANOTHER_ENV_VAR
    value: "anotherValue"
  - name: SECRET_USERNAME
    valueFrom:
      secretKeyRef:
        name: my-secret
        key: username
  - name: CONFIG_VALUE
    valueFrom:
      configMapKeyRef:
        name: my-configmap
        key: some-key

envFrom:
  enabled: false          # Enable or disable adding envFrom
  sources:
    - configMapRef:
        name: my-configmap-name    # Specify the name of your ConfigMap
    - secretRef:
        name: my-secret-name       # Specify the name of your Secret


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

volumeClaim:
  enabled: true
  name: gotify-data
  storageClassName: ""
  annotations: {}
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  selector: {}

backup:
  enabled: false
  backup:
    enabled: true
    schedule: '30 4 * * *'
  restore:
    enabled: true
    snapshot: latest
  keep:
    withinDaily: 1y
    withinMonthly: 5y
  repository:
    s3AccessKey: example
    s3SecretKey: example
    repository: s3:http://s3.example.com/gotify-backup
    repositoryPassword: example