{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gotify.fullname" . }}-secret
  labels:
    {{- include "gotify.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secret.data }}
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- if .Values.secret.stringData }}
stringData:
{{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
